version: '3.7'

services:
  mlapi1:
    build: mlapi:latest
    restart: on-failure
    volumes:
      - ./config.ini:/app/config.ini
    ports:
      - "5041:5040"

  mlapi2:
    build: mlapi:latest
    restart: on-failure
    ports:
      - "5042:5040"
    depends_on:
      - mlapi1

  gateway:
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5040:5040"
    command: 
      - bash
      - -c
      - nginx -g 'daemon off;'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mlapi1
      - mlapi2
      